# Generated by Django 4.1.4 on 2022-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='dateCompleted',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='note',
            name='finalDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(choices=[('pending', 'PENDIENTE'), ('in progress', 'EN PROCESO'), ('finished', 'FINALIZADO')], default='pending', max_length=15),
        ),
    ]
